- repo: local
  hooks: 
  - id: version-number
    name: Check consistency in version number
    entry: python ./.ci/precommit/fix_setup_version.py
    language: system
    files: '^(setup.json)'
    pass_filenames: false

# modernizer: make sure our code-base is Python 3 ready
- repo: https://github.com/python-modernize/python-modernize.git
  sha: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    exclude: >
      (?x)^(
        docs/.*|
      )$
    args:
      - --write
      - --nobackups
# Following are all the fixers in python-modernize.
# Those marked as 'done' were run at some point and their results checked
# and incorporated if necessary, but they can't be applied without breaking valid cases
#      - --fix=apply
#      - --fix=except
#      - --fix=exec
#      - --fix=execfile
#      - --fix=exitfunc
#      - --fix=funcattrs
#done:      - --fix=has_key
#optional:      - --fix=idioms
#done:      - --fix=long
#      - --fix=methodattrs
#      - --fix=ne
#      - --fix=numliterals
#      - --fix=operator
#      - --fix=paren
#      - --fix=reduce
#      - --fix=renames
#      - --fix=repr
#optional:      - --fix=set_literal
#      - --fix=standarderror
#      - --fix=sys_exc
#      - --fix=throw
#      - --fix=tuple_params
#      - --fix=types
#optional:      - --fix=ws_comma
#      - --fix=xreadlines
#      - --fix=basestring
#      - --fix=classic_division
#done:      - --fix=dict_six
#      - --fix=file
#      - --fix=filter
#      - --fix=import
#      - --fix=imports_six
#      - --fix=input_six
#      - --fix=int_long_tuple
#      - --fix=itertools_imports_six
#      - --fix=itertools_six
#      - --fix=map
#      - --fix=metaclass
#      - --fix=next
#optional:      - --fix=open
      - --fix=print
#      - --fix=raise
#      - --fix=raise_six
#      - --fix=unichr
#      - --fix=unicode
#      - --fix=unicode_future
#      - --fix=unicode_type
#      - --fix=urllib_six
#      - --fix=xrange_six
#      - --fix=zip
